In [1]:
import numpy as np

In [2]:
A = np.arange(5,15,2)
A 

array([ 5,  7,  9, 11, 13])

In [3]:
B = np.arange(19,33,3)
B

array([19, 22, 25, 28, 31])

In [6]:
np.random.rand(12,13)

array([[ 0.43385691,  0.15503296,  0.19860119,  0.65346609,  0.16774261,
         0.56058978,  0.84974275,  0.05887681,  0.27276929,  0.88750259,
         0.25141674,  0.05663906,  0.54186252],
       [ 0.2635477 ,  0.88291404,  0.42043263,  0.83565607,  0.92982761,
         0.79879409,  0.91323242,  0.37954769,  0.60198588,  0.44773903,
         0.70699903,  0.3892703 ,  0.94314732],
       [ 0.12593268,  0.97838364,  0.81297353,  0.3368167 ,  0.33501746,
         0.99619471,  0.22476839,  0.93321408,  0.41301684,  0.01808732,
         0.61321647,  0.22462791,  0.468457  ],
       [ 0.63765001,  0.13884884,  0.67648642,  0.65589694,  0.80931411,
         0.46202022,  0.40819602,  0.03863341,  0.16494124,  0.69603883,
         0.96849077,  0.19150476,  0.8968954 ],
       [ 0.25646945,  0.21928867,  0.70952192,  0.80569537,  0.84562245,
         0.54595757,  0.00684613,  0.19142737,  0.94387805,  0.80871064,
         0.73648968,  0.80105002,  0.16716087],
       [ 0.3894393 ,  0.619333

In [7]:
A

array([ 5,  7,  9, 11, 13])

In [8]:
A = np.append(A,19)
A

array([ 5,  7,  9, 11, 13, 19])

In [9]:
A = np.append(A,[3,55,34,553])
A

array([  5,   7,   9,  11,  13,  19,   3,  55,  34, 553])

In [13]:
np.diff(A,n=1)

array([  2,   2,   2,   2,   6, -16,  52, -21, 519])

In [12]:
np.diff(A,n=2)

array([  0,   0,   0,   4, -22,  68, -73, 540])

In [14]:
np.diff(A,n=3)

array([   0,    0,    4,  -26,   90, -141,  613])

In [21]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]

In [22]:
np.vstack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.vstack((b,a,c))

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [25]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
A

array([  5,   7,   9,  11,  13,  19,   3,  55,  34, 553])

In [29]:
A[2:5]   #N-1

array([ 9, 11])

In [30]:
A[0:3] 

array([5, 7, 9])

In [31]:
#A[lowerbound(inclusive): upperbound(exclusive)]

In [32]:
# broadcasting
A

array([  5,   7,   9,  11,  13,  19,   3,  55,  34, 553])

In [33]:
A+1

array([  6,   8,  10,  12,  14,  20,   4,  56,  35, 554])

In [34]:
A+[1,1,1,1,1,1,1,1,1,1]

array([  6,   8,  10,  12,  14,  20,   4,  56,  35, 554])

In [35]:
B

array([19, 22, 25, 28, 31])

In [37]:
A*-1

array([  -5,   -7,   -9,  -11,  -13,  -19,   -3,  -55,  -34, -553])