In [1]:
import numpy as np

In [3]:
A = np.arange(11,14) 
A = np.append(A,12)

In [4]:
A

array([11, 12, 13, 12])

In [5]:
set(A)

{11, 12, 13}

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.linspace(10,12,10)

array([ 10.        ,  10.22222222,  10.44444444,  10.66666667,
        10.88888889,  11.11111111,  11.33333333,  11.55555556,
        11.77777778,  12.        ])

In [12]:
np.random.rand(2,3)

array([[ 0.17308119,  0.03069699,  0.93340869],
       [ 0.01004991,  0.5889319 ,  0.41102689]])

In [15]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

In [17]:
A+3

array([14, 15, 16, 15])

In [18]:
a = [11, 12, 13, 12]